server:
  port: 8761
spring:
  application:
    name: eureka-server

# eureka configurations
# stop default this application register as client in eureka-server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


